# File: ai-text-detector/config.yaml
# Global configuration for paths, hyperparameters, and settings (no hard-coded values in code).
# The project code will read this file to get paths and parameters.
paths:
  raw_data: "data/final_dataset.csv"            # Path to original dataset CSV (must be provided)
  modern_data_dir: "data/modern_articles/"      # Directory for future "modern articles" CSVs
  cleaned_data: "data/cleaned_dataset.parquet"  # Path where cleaned full dataset will be saved
  train_data: "data/train_dataset.parquet"      # Path for training split
  val_data: "data/val_dataset.parquet"          # Path for validation split
  test_data: "data/test_dataset.parquet"        # Path for test split
  figures_dir: "diagrams/"                     # Directory to save figures/plots
  model_dirs:                                   # Directories to save fine-tuned models
    bert: "diagrams/bert/"
    roberta: "diagrams/roberta/"
    longformer: "diagrams/longformer/"
    final: "diagrams/final_model/"
  log_file: "logs/training.log"                # File for training logs
  session_log_json: "logs/sessions.json"       # File for saved session inputs (Dash)
  session_log_csv: "logs/sessions.csv"         # File for saved session inputs (Streamlit)

training:
  epochs:
    bert: 3
    roberta: 3
    longformer: 3
  batch_size:
    bert: 16
    roberta: 16
    longformer: 4              # Longformer uses smaller batch due to memory
  learning_rate: 2e-5
  max_length:
    bert_roberta: 512
    longformer: 4096
  gradient_accumulation_steps: 2
  use_focal_loss: false        # Whether to use focal loss (else use weighted CE)
  early_stopping_patience: 1   # Stop training if no improvement after this many epochs

model:
  label_mapping:               # Mapping of class names to numeric labels
    human: 0
    ai_paraphrased: 1
    ai_generated: 2

dashboard:
  enable_dash: true            # Flag to enable/disable running Dash app
  enable_streamlit: true       # Flag to enable/disable running Streamlit app
  theme: "light"               # UI theme preference (for future use)

logging:
  use_wandb: false             # Set true to enable Weights & Biases logging
  wandb_project: "ai_text_detector"
